# Generated by Django 4.2.3 on 2023-08-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='APIAPP.subject'),
        ),
    ]
