# Generated by Django 4.2.3 on 2023-08-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0005_remove_student_subject_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='APIAPP.subject'),
        ),
    ]
